[build]
  command = "npm install && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "16.14.0"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://excuse-machine.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
