[build]
  command = "rm -rf node_modules && npm ci && GENERATE_SOURCEMAP=false CI=false npm run build"
  publish = "build"
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
