[build]
  command = "CI=false npm ci && GENERATE_SOURCEMAP=false npm run build"
  publish = "build"
  functions = "netlify/functions"
  ignore = "false"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
