services:
  - type: web
    name: excuse-machine-api
    env: node
    rootDir: server
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: OPENAI_API_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://excuse-machine.netlify.app
    healthCheckPath: /api/health
    autoDeploy: true
