services:
  - type: web
    name: excuse-machine-api
    env: node
    region: ohio
    rootDir: server
    buildCommand: npm install --production
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    healthCheckTimeout: 120
    autoDeploy: true
    plan: free
