services:
  - type: web
    name: excuse-machine-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /
    autoDeploy: true
